# environment bundle for windows. Duplicate for other OSs to tackle dependency issuess
# environment bundle for windows. Duplicate for other OSs to tackle dependency issuess
name: ts_env
channels:
  - knime
  - conda-forge
  - defaults
dependencies:
  - knime-extension>=4.7.0
  - knime-python-base=4.7.1
  - markdown=3.4.1
  - numpy=1.24.1
  - pandas=1.5.2
  - pip=23.0.1
  - py4j=0.10.9.7
  - pyarrow=9.0.0
  - python=3.9.15
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2022.7.1
  - statsmodels=0.13.5
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - pip:
    - matplotlib==3.7.2
