org.tutorial.first_extension:
	src: C:\Users\Ali.Marvi\OneDrive - KNIME AG\Documents\Python Development for KAP\basic\tutorial_extension
	conda_env_path: C:\ProgramData\Anaconda3\envs\pzthon_env
	debug_mode: true