org.knime.time_series: # {group_id}.{name} from the knime.yml
  src: C:\Users\Ali.Marvi\OneDrive - KNIME AG\Documents\Python Development for KAP\TimeSeriesPyNodes\ # Path to folder containing the extension files
  conda_env_path: C:\ProgramData\Anaconda3\envs\ts_env # Path to the Python environment to use
  debug_mode: true # Optional line, if set to true, it will always use the latest changes of execute/configure, when that method is used within the KNIME Analytics Platform